### ISSUE TITLE
header

### ISSUE THREAD

**Issue by yfujii02** [f-ikeda/KC705_TIPS#2]
https://github.com/f-ikeda/KC705_TIPS/blob/05f85031d8274334ea44169c0268c710471ba01c/daq/daq_prototype.py#L37

ここは"0A BB 00 01 23 45 67 01 23 45 67"が正しい値？

**Comment by f-ikeda** [comment]
正しくは、
"AB B0 00 12 34 56 70 12 34 56 7BOARD_ID"
です。
(13 byte(データ長) - 2 byte(SPLCOUNT) = 11 byte)
https://github.com/yfujii02/TDCKC705/blob/62289ca472d036740fd14ec5a5c4be5e3dc44a1e/extinction.srcs/sources_1/new/DATA_BUF_singleBRAM2.v#L96

**Comment by yfujii02** [comment]
あー、header判定ように上位10bytesだけ使うので途中で途切れてるんですね。理解しました。
プログラムに関してですが、dataを受け取るclientと書き込みをする役割は分けて、できればthreadも分けるのがいいかもしれません。
https://www.tutorialspoint.com/python/python_multithreading.htm

**Comment by f-ikeda** [comment]
BOARD_IDはまだしばらくいじったりするので、判定に含めていませんでした。
はい、わかりました。
わからないことあったら、質問させていただきます(threadの実装とか)！
